import { db, pool } from "./client.js";
import { meals } from "./schema.js";

type SeedMeal = typeof meals.$inferInsert;

const starterMeals: SeedMeal[] = [
  {
    nameUz: "Osh (Palov)",
    nameEn: "Plov",
    cuisine: "uzbek",
    ingredients: ["rice", "beef", "carrot", "onion", "garlic", "oil"],
    cookTimeMinutes: 90,
    servingsMin: 5,
    servingsMax: 8,
    budgetTier: "normal",
    dietaryTags: [],
    recipeText: "Fry meat and onions, add carrots, layer rice on top, add water and simmer until rice is tender.",
  },
  {
    nameUz: "Qozonkabob",
    nameEn: "Qozon kabob",
    cuisine: "uzbek",
    ingredients: ["beef", "potato", "onion", "tomato", "pepper"],
    cookTimeMinutes: 50,
    servingsMin: 4,
    servingsMax: 5,
    budgetTier: "normal",
    dietaryTags: [],
    recipeText: "Layer meat, onions, and potatoes in a pot; stew until tender.",
  },
  {
    nameUz: "Dimlama",
    nameEn: "Dimlama",
    cuisine: "uzbek",
    ingredients: ["beef", "potato", "cabbage", "carrot", "onion", "tomato"],
    cookTimeMinutes: 55,
    servingsMin: 4,
    servingsMax: 6,
    budgetTier: "normal",
    dietaryTags: [],
    recipeText: "Layer vegetables and meat, cook covered on low heat without added water.",
  },
  {
    nameUz: "Shurpa",
    nameEn: "Shurpa",
    cuisine: "uzbek",
    ingredients: ["beef", "potato", "carrot", "onion", "tomato"],
    cookTimeMinutes: 60,
    servingsMin: 4,
    servingsMax: 6,
    budgetTier: "cheap",
    dietaryTags: [],
    recipeText: "Simmer meat and vegetables together into a hearty soup.",
  },
  {
    nameUz: "Mastava",
    nameEn: "Mastava",
    cuisine: "uzbek",
    ingredients: ["rice", "beef", "potato", "carrot", "onion", "tomato"],
    cookTimeMinutes: 45,
    servingsMin: 4,
    servingsMax: 5,
    budgetTier: "cheap",
    dietaryTags: [],
    recipeText: "A rice-based soup simmered with meat and vegetables.",
  },
  {
    nameUz: "Manti",
    nameEn: "Manti",
    cuisine: "central_asian",
    ingredients: ["dough", "beef", "onion", "pumpkin"],
    cookTimeMinutes: 75,
    servingsMin: 4,
    servingsMax: 6,
    budgetTier: "normal",
    dietaryTags: [],
    recipeText: "Fill dough parcels with seasoned meat and onion, steam until cooked.",
  },
  {
    nameUz: "Lagman",
    nameEn: "Lagman",
    cuisine: "central_asian",
    ingredients: ["noodles", "beef", "pepper", "onion", "tomato", "garlic"],
    cookTimeMinutes: 50,
    servingsMin: 3,
    servingsMax: 5,
    budgetTier: "normal",
    dietaryTags: [],
    recipeText: "Stir-fry meat and vegetables, combine with hand-pulled noodles in a savory broth.",
  },
  {
    nameUz: "Tovuq va kartoshka",
    nameEn: "Chicken with potatoes",
    cuisine: "international",
    ingredients: ["chicken", "potato", "onion", "garlic"],
    cookTimeMinutes: 40,
    servingsMin: 2,
    servingsMax: 5,
    budgetTier: "cheap",
    dietaryTags: [],
    recipeText: "Roast or pan-fry chicken pieces with potatoes and onion until golden.",
  },
  {
    nameUz: "Tovuqli pasta",
    nameEn: "Chicken pasta",
    cuisine: "european",
    ingredients: ["pasta", "chicken", "cream", "garlic", "cheese"],
    cookTimeMinutes: 30,
    servingsMin: 2,
    servingsMax: 4,
    budgetTier: "normal",
    dietaryTags: [],
    recipeText: "Cook pasta, toss with pan-seared chicken and a garlic cream sauce.",
  },
  {
    nameUz: "Bors",
    nameEn: "Borscht",
    cuisine: "russian",
    ingredients: ["beetroot", "cabbage", "potato", "beef", "carrot", "onion"],
    cookTimeMinutes: 60,
    servingsMin: 4,
    servingsMax: 6,
    budgetTier: "cheap",
    dietaryTags: [],
    recipeText: "Simmer beef broth with beetroot, cabbage, and root vegetables.",
  },
  {
    nameUz: "Sabzavotli qovurma",
    nameEn: "Vegetable stir-fry",
    cuisine: "asian",
    ingredients: ["broccoli", "carrot", "pepper", "onion", "soy_sauce", "garlic"],
    cookTimeMinutes: 20,
    servingsMin: 2,
    servingsMax: 4,
    budgetTier: "cheap",
    dietaryTags: ["vegetarian", "vegan"],
    recipeText: "Stir-fry mixed vegetables in garlic and soy sauce over high heat.",
  },
  {
    nameUz: "Yasmiq sho'rva",
    nameEn: "Lentil soup",
    cuisine: "international",
    ingredients: ["lentils", "carrot", "onion", "garlic", "tomato"],
    cookTimeMinutes: 35,
    servingsMin: 3,
    servingsMax: 5,
    budgetTier: "cheap",
    dietaryTags: ["vegetarian", "vegan"],
    recipeText: "Simmer lentils with onion, carrot, and tomato until soft.",
  },
  {
    nameUz: "Grill tovuq salat",
    nameEn: "Grilled chicken salad",
    cuisine: "international",
    ingredients: ["chicken", "lettuce", "tomato", "cucumber", "olive_oil"],
    cookTimeMinutes: 25,
    servingsMin: 1,
    servingsMax: 2,
    budgetTier: "normal",
    dietaryTags: ["no_pork"],
    recipeText: "Grill chicken breast and slice over a fresh vegetable salad.",
  },
  {
    nameUz: "Somsa",
    nameEn: "Somsa",
    cuisine: "uzbek",
    ingredients: ["dough", "beef", "onion", "pumpkin"],
    cookTimeMinutes: 70,
    servingsMin: 4,
    servingsMax: 8,
    budgetTier: "normal",
    dietaryTags: [],
    recipeText: "Fill pastry triangles with seasoned meat and onion, bake until golden.",
  },
  {
    nameUz: "Baliq va guruch",
    nameEn: "Fish with rice",
    cuisine: "international",
    ingredients: ["fish", "rice", "lemon", "garlic", "vegetables"],
    cookTimeMinutes: 35,
    servingsMin: 2,
    servingsMax: 4,
    budgetTier: "normal",
    dietaryTags: ["pescatarian"],
    recipeText: "Pan-fry or bake fish, serve over steamed rice with lemon and vegetables.",
  },
  {
    nameUz: "Tuxumli qovurdoq",
    nameEn: "Vegetable and egg scramble",
    cuisine: "international",
    ingredients: ["egg", "tomato", "pepper", "onion"],
    cookTimeMinutes: 15,
    servingsMin: 1,
    servingsMax: 3,
    budgetTier: "cheap",
    dietaryTags: ["vegetarian"],
    recipeText: "Saute vegetables, add beaten eggs and scramble together.",
  },
  {
    nameUz: "Go'shtsiz lagman",
    nameEn: "Vegetarian lagman",
    cuisine: "central_asian",
    ingredients: ["noodles", "pepper", "onion", "tomato", "garlic", "cabbage"],
    cookTimeMinutes: 40,
    servingsMin: 3,
    servingsMax: 5,
    budgetTier: "cheap",
    dietaryTags: ["vegetarian", "vegan"],
    recipeText: "Stir-fry vegetables and combine with noodles in a savory sauce, no meat.",
  },
  {
    nameUz: "Qovurilgan kartoshka va go'sht",
    nameEn: "Fried potatoes with meat",
    cuisine: "uzbek",
    ingredients: ["beef", "potato", "onion"],
    cookTimeMinutes: 35,
    servingsMin: 2,
    servingsMax: 4,
    budgetTier: "cheap",
    dietaryTags: [],
    recipeText: "Pan-fry diced potatoes with meat and onion until crisp and tender.",
  },
];

async function seed() {
  await db.insert(meals).values(starterMeals);
  console.log(`Seeded ${starterMeals.length} meals.`);
  await pool.end();
}

seed().catch((err) => {
  console.error(err);
  process.exitCode = 1;
});
