import { db, pool } from "./client.js";
import { meals } from "./schema.js";

type SeedMeal = typeof meals.$inferInsert;

const starterMeals: SeedMeal[] = [
  {
    nameUz: "Osh (Palov)",
    nameEn: "Plov",
    cuisine: "uzbek",
    ingredients: ["guruch", "mol go'shti", "sabzi", "piyoz", "sarimsoq", "yog'"],
    cookTimeMinutes: 90,
    servingsMin: 5,
    servingsMax: 8,
    budgetTier: "normal",
    dietaryTags: [],
    recipeText:
      "Go'sht va piyozni qovuring, sabzini qo'shing, ustidan guruch soling, suv quyib guruch yumshaguncha dimlang.",
  },
  {
    nameUz: "Qozonkabob",
    nameEn: "Qozon kabob",
    cuisine: "uzbek",
    ingredients: ["mol go'shti", "kartoshka", "piyoz", "pomidor", "qalampir"],
    cookTimeMinutes: 50,
    servingsMin: 4,
    servingsMax: 5,
    budgetTier: "normal",
    dietaryTags: [],
    recipeText: "Qozonga qatlab go'sht, piyoz va kartoshkani joylang; yumshaguncha dimlang.",
  },
  {
    nameUz: "Dimlama",
    nameEn: "Dimlama",
    cuisine: "uzbek",
    ingredients: ["mol go'shti", "kartoshka", "karam", "sabzi", "piyoz", "pomidor"],
    cookTimeMinutes: 55,
    servingsMin: 4,
    servingsMax: 6,
    budgetTier: "normal",
    dietaryTags: [],
    recipeText: "Sabzavot va go'shtni qatlab joylang, suv qo'shmasdan yopiq holda past olovda pishiring.",
  },
  {
    nameUz: "Shurpa",
    nameEn: "Shurpa",
    cuisine: "uzbek",
    ingredients: ["mol go'shti", "kartoshka", "sabzi", "piyoz", "pomidor"],
    cookTimeMinutes: 60,
    servingsMin: 4,
    servingsMax: 6,
    budgetTier: "cheap",
    dietaryTags: [],
    recipeText: "Go'sht va sabzavotlarni birga qaynatib, mazali sho'rva tayyorlang.",
  },
  {
    nameUz: "Mastava",
    nameEn: "Mastava",
    cuisine: "uzbek",
    ingredients: ["guruch", "mol go'shti", "kartoshka", "sabzi", "piyoz", "pomidor"],
    cookTimeMinutes: 45,
    servingsMin: 4,
    servingsMax: 5,
    budgetTier: "cheap",
    dietaryTags: [],
    recipeText: "Go'sht va sabzavotlar bilan qaynatilgan guruchli sho'rva.",
  },
  {
    nameUz: "Manti",
    nameEn: "Manti",
    cuisine: "central_asian",
    ingredients: ["xamir", "mol go'shti", "piyoz", "qovoq"],
    cookTimeMinutes: 75,
    servingsMin: 4,
    servingsMax: 6,
    budgetTier: "normal",
    dietaryTags: [],
    recipeText: "Xamirga ziravorlangan go'sht va piyoz solib, bug'da pishiring.",
  },
  {
    nameUz: "Lagman",
    nameEn: "Lagman",
    cuisine: "central_asian",
    ingredients: ["lag'mon xamiri", "mol go'shti", "qalampir", "piyoz", "pomidor", "sarimsoq"],
    cookTimeMinutes: 50,
    servingsMin: 3,
    servingsMax: 5,
    budgetTier: "normal",
    dietaryTags: [],
    recipeText: "Go'sht va sabzavotlarni qovuring, tortilgan lag'mon xamiri va sho'rva bilan aralashtiring.",
  },
  {
    nameUz: "Tovuq va kartoshka",
    nameEn: "Chicken with potatoes",
    cuisine: "international",
    ingredients: ["tovuq go'shti", "kartoshka", "piyoz", "sarimsoq"],
    cookTimeMinutes: 40,
    servingsMin: 2,
    servingsMax: 5,
    budgetTier: "cheap",
    dietaryTags: [],
    recipeText: "Tovuq bo'laklarini kartoshka va piyoz bilan tilla rangga kirguncha qovuring yoki pishiring.",
  },
  {
    nameUz: "Tovuqli pasta",
    nameEn: "Chicken pasta",
    cuisine: "european",
    ingredients: ["makaron", "tovuq go'shti", "qaymoq", "sarimsoq", "pishloq"],
    cookTimeMinutes: 30,
    servingsMin: 2,
    servingsMax: 4,
    budgetTier: "normal",
    dietaryTags: [],
    recipeText: "Makaronni qaynatib, qovurilgan tovuq va sarimsoqli qaymoq sousi bilan aralashtiring.",
  },
  {
    nameUz: "Bors",
    nameEn: "Borscht",
    cuisine: "russian",
    ingredients: ["lavlagi", "karam", "kartoshka", "mol go'shti", "sabzi", "piyoz"],
    cookTimeMinutes: 60,
    servingsMin: 4,
    servingsMax: 6,
    budgetTier: "cheap",
    dietaryTags: [],
    recipeText: "Mol go'shti sho'rvasini lavlagi, karam va ildizmevalar bilan qaynating.",
  },
  {
    nameUz: "Sabzavotli qovurma",
    nameEn: "Vegetable stir-fry",
    cuisine: "asian",
    ingredients: ["brokkoli", "sabzi", "qalampir", "piyoz", "soya sousi", "sarimsoq"],
    cookTimeMinutes: 20,
    servingsMin: 2,
    servingsMax: 4,
    budgetTier: "cheap",
    dietaryTags: ["vegetarian", "vegan"],
    recipeText: "Aralash sabzavotlarni kuchli olovda sarimsoq va soya sousida qovuring.",
  },
  {
    nameUz: "Yasmiq sho'rva",
    nameEn: "Lentil soup",
    cuisine: "international",
    ingredients: ["yasmiq", "sabzi", "piyoz", "sarimsoq", "pomidor"],
    cookTimeMinutes: 35,
    servingsMin: 3,
    servingsMax: 5,
    budgetTier: "cheap",
    dietaryTags: ["vegetarian", "vegan"],
    recipeText: "Yasmiqni piyoz, sabzi va pomidor bilan yumshaguncha qaynating.",
  },
  {
    nameUz: "Grill tovuq salat",
    nameEn: "Grilled chicken salad",
    cuisine: "international",
    ingredients: ["tovuq go'shti", "salat barglari", "pomidor", "bodring", "zaytun yog'i"],
    cookTimeMinutes: 25,
    servingsMin: 1,
    servingsMax: 2,
    budgetTier: "normal",
    dietaryTags: ["no_pork"],
    recipeText: "Tovuq ko'kragini grillda pishiring va yangi sabzavotli salat ustiga to'g'rab soling.",
  },
  {
    nameUz: "Somsa",
    nameEn: "Somsa",
    cuisine: "uzbek",
    ingredients: ["xamir", "mol go'shti", "piyoz", "qovoq"],
    cookTimeMinutes: 70,
    servingsMin: 4,
    servingsMax: 8,
    budgetTier: "normal",
    dietaryTags: [],
    recipeText: "Uchburchak xamirga ziravorlangan go'sht va piyoz solib, tilla rangga kirguncha pishiring.",
  },
  {
    nameUz: "Baliq va guruch",
    nameEn: "Fish with rice",
    cuisine: "international",
    ingredients: ["baliq", "guruch", "limon", "sarimsoq", "sabzavotlar"],
    cookTimeMinutes: 35,
    servingsMin: 2,
    servingsMax: 4,
    budgetTier: "normal",
    dietaryTags: ["pescatarian"],
    recipeText: "Baliqni qovuring yoki pishiring, bug'da pishirilgan guruch, limon va sabzavotlar bilan tortib bering.",
  },
  {
    nameUz: "Tuxumli qovurdoq",
    nameEn: "Vegetable and egg scramble",
    cuisine: "international",
    ingredients: ["tuxum", "pomidor", "qalampir", "piyoz"],
    cookTimeMinutes: 15,
    servingsMin: 1,
    servingsMax: 3,
    budgetTier: "cheap",
    dietaryTags: ["vegetarian"],
    recipeText: "Sabzavotlarni qovuring, chalingan tuxumni qo'shib birga qovuring.",
  },
  {
    nameUz: "Go'shtsiz lagman",
    nameEn: "Vegetarian lagman",
    cuisine: "central_asian",
    ingredients: ["lag'mon xamiri", "qalampir", "piyoz", "pomidor", "sarimsoq", "karam"],
    cookTimeMinutes: 40,
    servingsMin: 3,
    servingsMax: 5,
    budgetTier: "cheap",
    dietaryTags: ["vegetarian", "vegan"],
    recipeText: "Sabzavotlarni qovuring va mazali sousdagi lag'mon xamiri bilan aralashtiring, go'shtsiz.",
  },
  {
    nameUz: "Qovurilgan kartoshka va go'sht",
    nameEn: "Fried potatoes with meat",
    cuisine: "uzbek",
    ingredients: ["mol go'shti", "kartoshka", "piyoz"],
    cookTimeMinutes: 35,
    servingsMin: 2,
    servingsMax: 4,
    budgetTier: "cheap",
    dietaryTags: [],
    recipeText: "To'g'ralgan kartoshkani go'sht va piyoz bilan qarsillaguncha qovuring.",
  },
];

async function seed() {
  await db.insert(meals).values(starterMeals);
  console.log(`Seeded ${starterMeals.length} meals.`);
  await pool.end();
}

seed().catch((err) => {
  console.error(err);
  process.exitCode = 1;
});
