import { db, pool } from "./client.js";
import { meals, userMealInteractions } from "./schema.js";

type SeedMeal = typeof meals.$inferInsert;

const starterMeals: SeedMeal[] = [
  {
    nameUz: "Osh (Palov)",
    nameEn: "Plov",
    cuisine: "uzbek",
    ingredients: ["guruch", "mol go'shti", "sabzi", "piyoz", "sarimsoq", "yog'"],
    ingredientDetails: [
      "Guruch — 800 gramm",
      "Mol go'shti — 600 gramm",
      "Sabzi — 800 gramm",
      "Piyoz — 2 dona",
      "Sarimsoq — 1 bosh",
      "Yog' — 200 ml",
      "Tuz, zira — ta'biga qarab",
    ],
    cookTimeMinutes: 90,
    servingsMin: 5,
    servingsMax: 8,
    budgetTier: "normal",
    dietaryTags: [],
    recipeSteps: [
      "Qozonga yog' solib qizdiring, to'g'ralgan piyozni oltin rangga kirguncha qovuring.",
      "Go'shtni bo'laklab solib, hamma tomoni qovrilguncha aralashtiring.",
      "To'g'ralgan sabzini qo'shib 10 daqiqa qovuring.",
      "Ustidan issiq suv quyib, tuz va ziravorlar solib 40 daqiqa qaynating.",
      "Yuvilgan guruchni tekis qilib yoying, kerak bo'lsa suv qo'shing.",
      "Sarimsoq boshini o'rtasiga botiring, qopqoqni yopib past olovda 25-30 daqiqa dimlang.",
      "Guruch yumshagach aralashtirib issiq holda dasturxonga tortiring.",
    ],
  },
  {
    nameUz: "Qozonkabob",
    nameEn: "Qozon kabob",
    cuisine: "uzbek",
    ingredients: ["mol go'shti", "kartoshka", "piyoz", "pomidor", "qalampir"],
    ingredientDetails: [
      "Mol go'shti — 700 gramm",
      "Kartoshka — 800 gramm",
      "Piyoz — 2 dona",
      "Pomidor — 2 dona",
      "Qalampir — 1 dona",
      "Yog' — 100 ml",
      "Tuz, murch — ta'biga qarab",
    ],
    cookTimeMinutes: 50,
    servingsMin: 4,
    servingsMax: 5,
    budgetTier: "normal",
    dietaryTags: [],
    recipeSteps: [
      "Go'shtni yirik bo'laklarga to'g'rang, qozon tagiga birinchi qatlam qilib joylang.",
      "Ustiga halqa qilib kesilgan piyozni yoying.",
      "Kartoshkani yirik bo'laklab, keyingi qatlam qilib soling.",
      "Pomidor va qalampirni kesib eng ustiga joylang, tuz-murch soling.",
      "Ozgina suv va yog' quyib, qopqog'ini zich yoping.",
      "Past olovda 50 daqiqa go'sht va kartoshka yumshaguncha dimlang.",
    ],
  },
  {
    nameUz: "Dimlama",
    nameEn: "Dimlama",
    cuisine: "uzbek",
    ingredients: ["mol go'shti", "kartoshka", "karam", "sabzi", "piyoz", "pomidor"],
    ingredientDetails: [
      "Mol go'shti — 600 gramm",
      "Kartoshka — 600 gramm",
      "Karam — 400 gramm",
      "Sabzi — 300 gramm",
      "Piyoz — 2 dona",
      "Pomidor — 3 dona",
      "Yog', tuz, ziravorlar — ta'biga qarab",
    ],
    cookTimeMinutes: 55,
    servingsMin: 4,
    servingsMax: 6,
    budgetTier: "normal",
    dietaryTags: [],
    recipeSteps: [
      "Qozon tubiga yog' surtib, go'shtni bo'laklab birinchi qatlam qilib joylang.",
      "Ustiga halqalangan piyoz, so'ng to'g'ralgan sabzini qatlab soling.",
      "Keyingi qatlamga yirik kesilgan kartoshkani joylang.",
      "Karamni to'g'rab ustiga yoying, so'ngra bo'laklangan pomidorni soling.",
      "Har bir qatlamga ozgina tuz sepib, qopqog'ini zich yoping.",
      "Suv qo'shmasdan past olovda 55 daqiqa dimlang, oxirida aralashtirib bering.",
    ],
  },
  {
    nameUz: "Shurpa",
    nameEn: "Shurpa",
    cuisine: "uzbek",
    ingredients: ["mol go'shti", "kartoshka", "sabzi", "piyoz", "pomidor"],
    ingredientDetails: [
      "Mol go'shti (suyakli) — 600 gramm",
      "Kartoshka — 500 gramm",
      "Sabzi — 200 gramm",
      "Piyoz — 2 dona",
      "Pomidor — 2 dona",
      "Suv — 2.5 litr",
      "Tuz, ziravorlar — ta'biga qarab",
    ],
    cookTimeMinutes: 60,
    servingsMin: 4,
    servingsMax: 6,
    budgetTier: "cheap",
    dietaryTags: [],
    recipeSteps: [
      "Go'shtni sovuq suvga solib qaynating, ko'pigini olib tashlang.",
      "Go'sht yarim pishguncha 40 daqiqa past olovda qaynating.",
      "To'g'ralgan piyoz va sabzini qo'shib yana 10 daqiqa qaynating.",
      "Kartoshkani yirik bo'laklab soling, yumshaguncha pishiring.",
      "Pomidor va ziravorlarni qo'shib yana 10 daqiqa qaynating.",
      "Tuz solib, ko'katlar sepib issiq holda tortiring.",
    ],
  },
  {
    nameUz: "Mastava",
    nameEn: "Mastava",
    cuisine: "uzbek",
    ingredients: ["guruch", "mol go'shti", "kartoshka", "sabzi", "piyoz", "pomidor"],
    ingredientDetails: [
      "Mol go'shti — 400 gramm",
      "Guruch — 150 gramm",
      "Kartoshka — 300 gramm",
      "Sabzi — 150 gramm",
      "Piyoz — 1 dona",
      "Pomidor — 2 dona",
      "Suv — 2 litr",
    ],
    cookTimeMinutes: 45,
    servingsMin: 4,
    servingsMax: 5,
    budgetTier: "cheap",
    dietaryTags: [],
    recipeSteps: [
      "Go'shtni mayda bo'laklab qovuring, piyoz va sabzini qo'shib birga qovuring.",
      "Pomidorni qo'shib yana 5 daqiqa qovuring.",
      "Ustidan issiq suv quyib qaynating.",
      "Kartoshkani mayda to'g'rab soling, yarim pishguncha qaynating.",
      "Yuvilgan guruchni qo'shib, guruch yumshaguncha 20 daqiqa qaynating.",
      "Tuz solib, ko'katlar bilan issiq holda tortiring.",
    ],
  },
  {
    nameUz: "Manti",
    nameEn: "Manti",
    cuisine: "central_asian",
    ingredients: ["xamir", "mol go'shti", "piyoz", "qovoq"],
    ingredientDetails: [
      "Un (xamir uchun) — 500 gramm",
      "Mol go'shti (mayda to'g'ralgan) — 500 gramm",
      "Qovoq — 300 gramm",
      "Piyoz — 3 dona",
      "Tuz, murch, zira — ta'biga qarab",
    ],
    cookTimeMinutes: 75,
    servingsMin: 4,
    servingsMax: 6,
    budgetTier: "normal",
    dietaryTags: [],
    recipeSteps: [
      "Undan qattiqroq xamir qorib, 30 daqiqa dam bering.",
      "Go'sht, mayda to'g'ralgan qovoq va piyozni aralashtirib, tuz-ziravor soling.",
      "Xamirni yupqa yoyib, kvadrat bo'laklarga kesing.",
      "Har bir bo'lakka fars qo'yib, mantining qulay shaklida yoping.",
      "Mantiqasqonni yog'lab, mantilarni bir-biriga tegmasdan joylashtiring.",
      "Qaynayotgan bug'da 40-45 daqiqa pishiring.",
    ],
  },
  {
    nameUz: "Lagman",
    nameEn: "Lagman",
    cuisine: "central_asian",
    ingredients: ["lag'mon xamiri", "mol go'shti", "qalampir", "piyoz", "pomidor", "sarimsoq"],
    ingredientDetails: [
      "Lag'mon xamiri (tortilgan) — 400 gramm",
      "Mol go'shti — 400 gramm",
      "Qalampir — 2 dona",
      "Piyoz — 2 dona",
      "Pomidor — 3 dona",
      "Sarimsoq — 4 bo'lak",
      "Yog', ziravorlar — ta'biga qarab",
    ],
    cookTimeMinutes: 50,
    servingsMin: 3,
    servingsMax: 5,
    budgetTier: "normal",
    dietaryTags: [],
    recipeSteps: [
      "Go'shtni ingichka to'g'rab, qaynagan yog'da qovuring.",
      "Piyoz va qalampirni qo'shib 5 daqiqa qovuring.",
      "Pomidor va sarimsoqni solib, ozgina suv qo'shib 15 daqiqa qaynating — sous tayyor.",
      "Lag'mon xamirini qaynayotgan suvda pishirib, suvini to'kib oling.",
      "Xamirni likopchaga solib, ustidan tayyor sous quying.",
      "Ko'katlar sepib issiq holda tortiring.",
    ],
  },
  {
    nameUz: "Tovuq va kartoshka",
    nameEn: "Chicken with potatoes",
    cuisine: "international",
    ingredients: ["tovuq go'shti", "kartoshka", "piyoz", "sarimsoq"],
    ingredientDetails: [
      "Tovuq go'shti — 600 gramm",
      "Kartoshka — 600 gramm",
      "Piyoz — 1 dona",
      "Sarimsoq — 3 bo'lak",
      "Yog' — 60 ml",
      "Tuz, murch, ziravorlar — ta'biga qarab",
    ],
    cookTimeMinutes: 40,
    servingsMin: 2,
    servingsMax: 5,
    budgetTier: "cheap",
    dietaryTags: [],
    recipeSteps: [
      "Tovuq bo'laklarini tuz va ziravorlar bilan ishqalang.",
      "Kartoshkani bo'laklarga to'g'rang, yog' va ziravorlar bilan aralashtiring.",
      "Tovuq va kartoshkani qovurish tovasiga bir tekis joylang.",
      "180°C da 35-40 daqiqa yoki tovada tilla rang bo'lguncha pishiring.",
      "Piyoz va sarimsoqni oxirgi 10 daqiqada qo'shing.",
      "Tayyor bo'lgach issiq holda dasturxonga tortiring.",
    ],
  },
  {
    nameUz: "Tovuqli pasta",
    nameEn: "Chicken pasta",
    cuisine: "european",
    ingredients: ["makaron", "tovuq go'shti", "qaymoq", "sarimsoq", "pishloq"],
    ingredientDetails: [
      "Makaron — 300 gramm",
      "Tovuq go'shti (filya) — 400 gramm",
      "Qaymoq — 200 ml",
      "Sarimsoq — 2 bo'lak",
      "Pishloq (uvalangan) — 100 gramm",
      "Yog', tuz, murch — ta'biga qarab",
    ],
    cookTimeMinutes: 30,
    servingsMin: 2,
    servingsMax: 4,
    budgetTier: "normal",
    dietaryTags: [],
    recipeSteps: [
      "Makaronni tuzlangan suvda qaynatib, suvini to'kib oling.",
      "Tovuqni mayda kesib, yog'da tilla rang bo'lguncha qovuring.",
      "Maydalangan sarimsoqni qo'shib bir daqiqa qovuring.",
      "Qaymoqni quyib, past olovda 5 daqiqa qaynating — sous qalinlashadi.",
      "Tayyor makaronni sousga solib aralashtiring.",
      "Uvalangan pishloq sepib, issiq holda tortiring.",
    ],
  },
  {
    nameUz: "Bors",
    nameEn: "Borscht",
    cuisine: "russian",
    ingredients: ["lavlagi", "karam", "kartoshka", "mol go'shti", "sabzi", "piyoz"],
    ingredientDetails: [
      "Mol go'shti — 500 gramm",
      "Lavlagi — 2 dona",
      "Karam — 300 gramm",
      "Kartoshka — 300 gramm",
      "Sabzi — 1 dona",
      "Piyoz — 1 dona",
      "Sirka yoki limon sharbati — 1 osh qoshiq",
    ],
    cookTimeMinutes: 60,
    servingsMin: 4,
    servingsMax: 6,
    budgetTier: "cheap",
    dietaryTags: [],
    recipeSteps: [
      "Go'shtni suvga solib qaynating, sho'rva tayyorlang (40 daqiqa).",
      "Lavlagi va sabzini mayda to'g'rab, ozgina sirka bilan qovuring — bu rangni saqlaydi.",
      "Sho'rvaga to'g'ralgan kartoshkani solib qaynating.",
      "Karamni ingichka to'g'rab qo'shing.",
      "Qovurilgan lavlagi-sabzi aralashmasini soling, 15 daqiqa qaynating.",
      "Tuz solib, qaymoq bilan issiq holda tortiring.",
    ],
  },
  {
    nameUz: "Sabzavotli qovurma",
    nameEn: "Vegetable stir-fry",
    cuisine: "asian",
    ingredients: ["brokkoli", "sabzi", "qalampir", "piyoz", "soya sousi", "sarimsoq"],
    ingredientDetails: [
      "Brokkoli — 300 gramm",
      "Sabzi — 150 gramm",
      "Qalampir — 2 dona",
      "Piyoz — 1 dona",
      "Sarimsoq — 2 bo'lak",
      "Soya sousi — 3 osh qoshiq",
      "Yog' — 2 osh qoshiq",
    ],
    cookTimeMinutes: 20,
    servingsMin: 2,
    servingsMax: 4,
    budgetTier: "cheap",
    dietaryTags: ["vegetarian", "vegan"],
    recipeSteps: [
      "Barcha sabzavotlarni bir xil o'lchamda to'g'rang.",
      "Vokni yoki tovani kuchli olovda qizdirib, yog' soling.",
      "Sarimsoq va piyozni 1 daqiqa qovuring.",
      "Sabzi va qalampirni qo'shib 3-4 daqiqa qovuring.",
      "Brokkolini solib, soya sousi quying, yana 3 daqiqa qovuring.",
      "Sabzavotlar qarsillagan holida darhol dasturxonga tortiring.",
    ],
  },
  {
    nameUz: "Yasmiq sho'rva",
    nameEn: "Lentil soup",
    cuisine: "international",
    ingredients: ["yasmiq", "sabzi", "piyoz", "sarimsoq", "pomidor"],
    ingredientDetails: [
      "Yasmiq (qizil) — 250 gramm",
      "Sabzi — 150 gramm",
      "Piyoz — 1 dona",
      "Sarimsoq — 2 bo'lak",
      "Pomidor — 2 dona (yoki 1 osh qoshiq pomidor pastasi)",
      "Suv — 1.5 litr",
    ],
    cookTimeMinutes: 35,
    servingsMin: 3,
    servingsMax: 5,
    budgetTier: "cheap",
    dietaryTags: ["vegetarian", "vegan"],
    recipeSteps: [
      "Piyoz va sabzini mayda to'g'rab, yog'da yumshaguncha qovuring.",
      "Pomidorni qo'shib 5 daqiqa qovuring.",
      "Yuvilgan yasmiqni solib, ustidan suv quying.",
      "Qaynagach past olovga o'tkazib, yasmiq yumshaguncha 20-25 daqiqa qaynating.",
      "Sarimsoq va tuz qo'shing, xohlasangiz blenderdan o'tkazing.",
      "Ko'katlar sepib issiq holda tortiring.",
    ],
  },
  {
    nameUz: "Grill tovuq salat",
    nameEn: "Grilled chicken salad",
    cuisine: "international",
    ingredients: ["tovuq go'shti", "salat barglari", "pomidor", "bodring", "zaytun yog'i"],
    ingredientDetails: [
      "Tovuq ko'kragi — 300 gramm",
      "Salat barglari — 100 gramm",
      "Pomidor — 1 dona",
      "Bodring — 1 dona",
      "Zaytun yog'i — 2 osh qoshiq",
      "Limon sharbati — 1 osh qoshiq",
      "Tuz, murch — ta'biga qarab",
    ],
    cookTimeMinutes: 25,
    servingsMin: 1,
    servingsMax: 2,
    budgetTier: "normal",
    dietaryTags: ["no_pork"],
    recipeSteps: [
      "Tovuq ko'kragini tuz-murch bilan ishqalang.",
      "Grill yoki tovada har tomonini 6-7 daqiqadan pishiring.",
      "Salat barglarini yirtib, pomidor va bodringni to'g'rang.",
      "Sabzavotlarni likopchaga joylang.",
      "Pishgan tovuqni bo'laklab, salat ustiga qo'ying.",
      "Zaytun yog'i va limon sharbati bilan tatib bering.",
    ],
  },
  {
    nameUz: "Somsa",
    nameEn: "Somsa",
    cuisine: "uzbek",
    ingredients: ["xamir", "mol go'shti", "piyoz", "qovoq"],
    ingredientDetails: [
      "Un (xamir uchun) — 500 gramm",
      "Mol go'shti (mayda to'g'ralgan) — 500 gramm",
      "Qovoq — 300 gramm",
      "Piyoz — 3 dona",
      "Tuz, murch, zira — ta'biga qarab",
    ],
    cookTimeMinutes: 70,
    servingsMin: 4,
    servingsMax: 8,
    budgetTier: "normal",
    dietaryTags: [],
    recipeSteps: [
      "Undan yumshoq xamir qorib, 20 daqiqa dam bering.",
      "Go'sht, mayda to'g'ralgan qovoq va piyozni aralashtirib fars tayyorlang.",
      "Xamirni bo'laklarga bo'lib, yupqa yoying.",
      "Har biriga fars solib, uchburchak shaklda yoping.",
      "Tandirga yopishtiring yoki tavaga terib joylashtiring.",
      "200°C da 35-40 daqiqa tilla rang bo'lguncha pishiring.",
    ],
  },
  {
    nameUz: "Baliq va guruch",
    nameEn: "Fish with rice",
    cuisine: "international",
    ingredients: ["baliq", "guruch", "limon", "sarimsoq", "sabzavotlar"],
    ingredientDetails: [
      "Baliq filesi — 500 gramm",
      "Guruch — 250 gramm",
      "Limon — 1 dona",
      "Sarimsoq — 2 bo'lak",
      "Sabzavotlar (sabzi, qalampir) — 200 gramm",
      "Yog', tuz — ta'biga qarab",
    ],
    cookTimeMinutes: 35,
    servingsMin: 2,
    servingsMax: 4,
    budgetTier: "normal",
    dietaryTags: ["pescatarian"],
    recipeSteps: [
      "Guruchni yuvib, bug'da yoki qaynatib pishiring.",
      "Baliqni tuz, limon sharbati va sarimsoq bilan marinadlang.",
      "Tovada yoki pechda baliqni har tomonidan 4-5 daqiqadan pishiring.",
      "Sabzavotlarni mayda to'g'rab, alohida qovuring.",
      "Pishgan guruchni likopchaga solib, ustiga sabzavotlarni joylang.",
      "Baliqni ustiga qo'yib, limon bo'lagi bilan tortiring.",
    ],
  },
  {
    nameUz: "Tuxumli qovurdoq",
    nameEn: "Vegetable and egg scramble",
    cuisine: "international",
    ingredients: ["tuxum", "pomidor", "qalampir", "piyoz"],
    ingredientDetails: [
      "Tuxum — 4 dona",
      "Pomidor — 2 dona",
      "Qalampir — 1 dona",
      "Piyoz — 1 dona",
      "Yog' — 2 osh qoshiq",
      "Tuz — ta'biga qarab",
    ],
    cookTimeMinutes: 15,
    servingsMin: 1,
    servingsMax: 3,
    budgetTier: "cheap",
    dietaryTags: ["vegetarian"],
    recipeSteps: [
      "Piyoz va qalampirni mayda to'g'rab, yog'da yumshaguncha qovuring.",
      "Pomidorni qo'shib 5 daqiqa qovuring, suvi qaynab ketishi kerak.",
      "Tuxumlarni bir idishga chaqib, tuz qo'shib chalib oling.",
      "Chalingan tuxumni tovaga quying.",
      "Past olovda asta-sekin aralashtirib, tuxum quyuqlashguncha pishiring.",
      "Issiq holda non bilan tortiring.",
    ],
  },
  {
    nameUz: "Go'shtsiz lagman",
    nameEn: "Vegetarian lagman",
    cuisine: "central_asian",
    ingredients: ["lag'mon xamiri", "qalampir", "piyoz", "pomidor", "sarimsoq", "karam"],
    ingredientDetails: [
      "Lag'mon xamiri (tortilgan) — 400 gramm",
      "Qalampir — 2 dona",
      "Piyoz — 2 dona",
      "Pomidor — 3 dona",
      "Karam — 200 gramm",
      "Sarimsoq — 4 bo'lak",
      "Yog', ziravorlar — ta'biga qarab",
    ],
    cookTimeMinutes: 40,
    servingsMin: 3,
    servingsMax: 5,
    budgetTier: "cheap",
    dietaryTags: ["vegetarian", "vegan"],
    recipeSteps: [
      "Piyoz, qalampir va karamni ingichka to'g'rab, yog'da qovuring.",
      "Pomidor va sarimsoqni qo'shib 10 daqiqa qovuring.",
      "Ozgina suv qo'shib, 10 daqiqa qaynatib sous tayyorlang.",
      "Lag'mon xamirini qaynayotgan suvda pishirib, suvini to'kib oling.",
      "Xamirni likopchaga solib, ustidan sous quying.",
      "Ko'katlar sepib, go'shtsiz holda issiq tortiring.",
    ],
  },
  {
    nameUz: "Qovurilgan kartoshka va go'sht",
    nameEn: "Fried potatoes with meat",
    cuisine: "uzbek",
    ingredients: ["mol go'shti", "kartoshka", "piyoz"],
    ingredientDetails: [
      "Mol go'shti — 400 gramm",
      "Kartoshka — 600 gramm",
      "Piyoz — 1 dona",
      "Yog' — 80 ml",
      "Tuz, murch — ta'biga qarab",
    ],
    cookTimeMinutes: 35,
    servingsMin: 2,
    servingsMax: 4,
    budgetTier: "cheap",
    dietaryTags: [],
    recipeSteps: [
      "Go'shtni mayda kubik shaklida to'g'rang.",
      "Tovada yog'ni qizdirib, go'shtni qarsillaguncha qovuring.",
      "Kartoshkani mayda kubik qilib to'g'rab, alohida qovuring.",
      "Piyozni halqalab, go'sht bilan birga qovuring.",
      "Qovurilgan kartoshka va go'shtni birlashtiring.",
      "Tuz-murch solib, aralashtirib issiq holda tortiring.",
    ],
  },
];

async function seed() {
  // Clear interactions first — they reference meals via a foreign key.
  await db.delete(userMealInteractions);
  await db.delete(meals);
  await db.insert(meals).values(starterMeals);
  console.log(`Seeded ${starterMeals.length} meals.`);
  await pool.end();
}

seed().catch((err) => {
  console.error(err);
  process.exitCode = 1;
});
